# Generated by Django 3.1.6 on 2021-04-03 08:18

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('marketCap', models.CharField(max_length=255, verbose_name='marketCap')),
                ('currentPrice', models.CharField(max_length=255, verbose_name='currentPrice')),
                ('stockPE', models.CharField(max_length=255, verbose_name='stockPE')),
                ('dividendYield', models.CharField(max_length=255, verbose_name='dividendYield')),
                ('roce', models.CharField(max_length=255, verbose_name='roce')),
                ('roe', models.CharField(max_length=255, verbose_name='roe')),
                ('debtToEquity', models.CharField(max_length=255, verbose_name='debtToEquity')),
                ('eps', models.CharField(max_length=255, verbose_name='eps')),
                ('reserves', models.CharField(max_length=255, verbose_name='reserves')),
                ('debt', models.CharField(max_length=255, verbose_name='debt')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
